//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001240399_Trinh_Huu_Kien_Quoc_Bai3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public string MaLop { get; set; }
        public string MaKhoa { get; set; }
    
        public virtual Khoa Khoa { get; set; }
    }
}
