//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001240399_Trinh_Huu_Kien_Quoc_KTL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETDATPHONG
    {
        public int MaCT { get; set; }
        public Nullable<int> MaDP { get; set; }
        public string MaPT { get; set; }
        public Nullable<int> SL { get; set; }
    
        public virtual DATPHONG DATPHONG { get; set; }
        public virtual PHUTHU PHUTHU { get; set; }
    }
}
