//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2001240399_Trinh_Huu_Kien_Quoc_KTL2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.DATPHONGs = new HashSet<DATPHONG>();
        }
    
        public string MaPhong { get; set; }
        public string TenPhong { get; set; }
        public Nullable<int> SucChua { get; set; }
        public Nullable<decimal> GiaPhong { get; set; }
        public Nullable<int> KieuPhong { get; set; }
        public string MaNhom { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DATPHONG> DATPHONGs { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
    }
}
