//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MASANPHAM { get; set; }
        public string TENSANPHAM { get; set; }
        public string MALOAISANPHAM { get; set; }
        public Nullable<double> DONGIA { get; set; }
    
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
        public virtual TONKHO_NGAY TONKHO_NGAY { get; set; }
    }
}
