-- 1. TẠO CƠ SỞ DỮ LIỆU
CREATE DATABASE QLHangHoa;
GO

USE QLHangHoa;
GO

-- 2. TẠO BẢNG & KHÓA

CREATE TABLE LOAISANPHAM (
    MALOAISANPHAM VARCHAR(10) PRIMARY KEY,
    TENLOAISANPHAM NVARCHAR(100) NOT NULL
);

CREATE TABLE SANPHAM (
    MASANPHAM VARCHAR(10) PRIMARY KEY,
    TENSANPHAM NVARCHAR(100) NOT NULL,
    MALOAISANPHAM VARCHAR(10),
    DONGIA DECIMAL(18, 0) NOT NULL,
    CONSTRAINT FK_SANPHAM_LOAISP FOREIGN KEY (MALOAISANPHAM) REFERENCES LOAISANPHAM(MALOAISANPHAM)
);

CREATE TABLE NHACUNGCAP (
    MANCC VARCHAR(10) PRIMARY KEY,
    TENNCC NVARCHAR(100) NOT NULL,
    DIACHI NVARCHAR(200)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(20) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    NamSinh INT,
    DienThoai VARCHAR(15),
    Email VARCHAR(50),
    MatKhau VARCHAR(50) NOT NULL,
    VaiTro NVARCHAR(50) NOT NULL
);

CREATE TABLE PHIEUNHAP (
    MAPHIEUNHAP VARCHAR(10) PRIMARY KEY,
    MANCC VARCHAR(10),
    NGAYNHAP DATETIME NOT NULL,
    THANHTIEN DECIMAL(18, 0) DEFAULT 0,
    MANV VARCHAR(20),
    CONSTRAINT FK_PHIEUNHAP_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC),
    CONSTRAINT FK_PHIEUNHAP_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE CHITIETPHIEUNHAP (
    MAPHIEUNHAP VARCHAR(10),
    MASANPHAM VARCHAR(10),
    DONGIA DECIMAL(18, 0) NOT NULL,
    SOLUONG INT NOT NULL,
    PRIMARY KEY (MAPHIEUNHAP, MASANPHAM),
    CONSTRAINT FK_CTPN_PHIEUNHAP FOREIGN KEY (MAPHIEUNHAP) REFERENCES PHIEUNHAP(MAPHIEUNHAP),
    CONSTRAINT FK_CTPN_SANPHAM FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);

CREATE TABLE TONKHO_NGAY (
    MASANPHAM VARCHAR(10) PRIMARY KEY,
    SOLUONGTON INT DEFAULT 0,
    CONSTRAINT FK_TONKHO_SANPHAM FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
);
GO

-- 3. CHÈN DỮ LIỆU MẪU

-- Nhân viên (Phục vụ Test Phân Quyền)
INSERT INTO NHANVIEN (MaNV, TenNV, NamSinh, DienThoai, Email, MatKhau, VaiTro) VALUES 
('NV01', N'Nguyễn Văn Hùng', 1988, '0901234567', 'quanly@qlhanghoa.com', '123', N'Quản lý'),
('NV02', N'Trần Thị Lan', 1994, '0912345678', 'kho@qlhanghoa.com', '123', N'Nhân viên kho'),
('NV03', N'Phạm Thị Hạnh', 1997, '0923456789', 'banhang@qlhanghoa.com', '123', N'Nhân viên bán hàng');

-- Loại Sản Phẩm
INSERT INTO LOAISANPHAM (MALOAISANPHAM, TENLOAISANPHAM) VALUES
('LSP01', N'Tivi'),
('LSP02', N'Tủ lạnh'),
('LSP03', N'Máy lạnh');

-- Sản phẩm
INSERT INTO SANPHAM (MASANPHAM, TENSANPHAM, MALOAISANPHAM, DONGIA) VALUES
('SP01', N'Smart TV Samsung 55 inch 4K', 'LSP01', 12000000),
('SP02', N'Smart TV Sony 65 inch Google', 'LSP01', 20000000),
('SP03', N'Tủ lạnh Samsung Inverter 380L', 'LSP02', 15000000),
('SP04', N'Máy lạnh Daikin Inverter 1.5HP', 'LSP03', 10000000);

-- Tồn Kho Ban Đầu
INSERT INTO TONKHO_NGAY (MASANPHAM, SOLUONGTON) VALUES
('SP01', 10),
('SP02', 5),
('SP03', 15),
('SP04', 20);

-- Nhà Cung Cấp
INSERT INTO NHACUNGCAP (MANCC, TENNCC, DIACHI) VALUES
('NCC01', N'Điện máy Chợ lớn', N'Quận 5, TP.HCM'),
('NCC02', N'Thiên Hòa', N'Quận 10, TP.HCM'),
('NCC03', N'LG Electronics Việt Nam', N'Quận 1, TP.HCM');
GO
