//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai6.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KetQua
    {
        public string MaSinhVien { get; set; }
        public string MaMonHoc { get; set; }
        public string NamHoc { get; set; }
        public int HocKy { get; set; }
        public Nullable<double> Diem { get; set; }
    
        public virtual MonHoc MonHoc { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
