//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bai2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Khoa
    {
        public Khoa()
        {
            this.Lops = new HashSet<Lop>();
        }
    
        public string MaKhoa { get; set; }
        public string TenKhoa { get; set; }
    
        public virtual ICollection<Lop> Lops { get; set; }
    }
}
