// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Bai3.Models;

public partial class Lop
{
    public string MaLop { get; set; }

    public string MaKhoa { get; set; }

    public virtual Khoa MaKhoaNavigation { get; set; }
}